# 注意这里的vertion是docker-compose yaml格式的version 不同的version支持不同的语法
version: '3'
services:
    nginx:
        # 依赖关系 先跑php
        depends_on:
            - php
        #image: nginx:${NGINX_VERSION}
        build: nginx/
        # 数据卷
        volumes:
            - ${LOCAL_STOARGE_PATH}/nginx/conf.d:/etc/nginx/conf.d:ro
            # 证书挂载保存，需要用的时候，进容器执行 sh /usr/local/bin/docker-make-ssl.sh，然后cp -R /etc/nginx/ssl /etc/nginx/ca
            - ${LOCAL_STOARGE_PATH}/nginx/ca:/etc/nginx/ca
            - ${LOCAL_WEB_PATH}:/works
        # 端口映射
        ports:
            - 80:80
            - 443:443

        # 容器名称
        container_name: nginx
        #restart: always
    php:
        build: php/
        volumes:
            - ${LOCAL_WEB_PATH}:/works
        container_name: php
        #restart: always
    # MySQL数据库
#    mysql:
#        image: mysql:${MYSQL_VERSION}
#        command: --max_allowed_packet=20971520
#        # 配置环境变量
#        environment:
#            MYSQL_USER: root
#            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#            MYSQL_ROOT_HOST: "%"
#        ports:
#            - 3306:3306
#        volumes:
#            # mysql 配置文件
#            - ${LOCAL_STOARGE_PATH}/mysql/conf.d:/etc/mysql/conf.d:ro
#            # mysql 配置文件
#            - ${LOCAL_STOARGE_PATH}/mysql/mysql.conf.d:/etc/mysql/mysql.conf.d:ro
#            # mysql 数据库
#            - ${LOCAL_STOARGE_PATH}/mysql/db:/var/lib/mysql
#            # mysql 日志
#            - ${LOCAL_STOARGE_PATH}/mysql/logs:/var/log/mysql
#        container_name: mysql
        #restart: always
#    redis:
#        image: redis:${REDIS_VERSION}
#        volumes:
#            # redis 配置文件
#            - ${LOCAL_STOARGE_PATH}/redis/conf.d/redis.conf:/etc/redis/redis.conf:ro
#            # redis 持久化数据存储
#            - ${LOCAL_STOARGE_PATH}/redis/db:/data/redis
#            # 以配置文件启动 redis
#        ports:
#            - 6379:6379
#        container_name: redis
        #restart: always
    #mongo:
#        image: mongo:latest
#        volumes: 
#            # Windows 磁盘是NTFS/FAT32，不支持Ext4大文件，不能挂载，需要注释下行， Windows下无解
#            #- ${LOCAL_STOARGE_PATH}/mongo/db:/data/db
#            - ${LOCAL_STOARGE_PATH}/mongo/logs:/var/log/mongodb
#        ports: 
#            - 27017:27017
#        container_name: mongo
        #restart: always
